### ISSUE TITLE
RTD fails to create documentation

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.intid#10]
See http://readthedocs.org/projects/zopeintid/builds/ for a list of failing builds.

**Comment by jamadden** [comment]
Thanks. Looks like it's the zope.interface problem. Sometimes this can be fixed by changing the interpreter between 2 and 3 (no idea why) but I tried that and it didn't work. The other fix is to add the problematic requirement to doc-requirements.txt.

**Comment by jamadden** [comment]
That greened them up again! Thanks again.
